//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIKINGO_PROJECT.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int ID_detalle { get; set; }
        public int cantidad { get; set; }
        public int id_factura { get; set; }
        public Nullable<int> id_producto { get; set; }
        public decimal precioUnitario { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
