//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIKINGO_PROJECT.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodDefectuoso
    {
        public int id_proDef { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
        public string motivo { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Motivo Motivo1 { get; set; }
    }
}
