//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIKINGO_PROJECT.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string usuario1 { get; set; }
        public string contraseña { get; set; }
        public string tipo_usuario { get; set; }
        public int ID_usuario { get; set; }
        public int id_persona { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Tipo_usuario Tipo_usuario1 { get; set; }
    }
}
